var tree = [["bnetlib","bnetlib.html","",
                [["Connection","bnetlib\/Connection.html","",
                [["AbstractConnection","bnetlib\/Connection\/AbstractConnection.html","",
                [        ]],["ConnectionInterface","bnetlib\/Connection\/ConnectionInterface.html","",
                [        ]],["Stub","bnetlib\/Connection\/Stub.html"," < AbstractConnection",
                [        ]],["ZendFramework","bnetlib\/Connection\/ZendFramework.html"," < AbstractConnection",
                [        ]]        ]],["Exception","bnetlib\/Exception.html","",
                [["BadMethodCallException","bnetlib\/Exception\/BadMethodCallException.html"," < BadMethodCallException",
                [        ]],["CacheException","bnetlib\/Exception\/CacheException.html"," < RuntimeException",
                [        ]],["ClientException","bnetlib\/Exception\/ClientException.html"," < Exception",
                [        ]],["DomainException","bnetlib\/Exception\/DomainException.html"," < DomainException",
                [        ]],["ExceptionInterface","bnetlib\/Exception\/ExceptionInterface.html","",
                [        ]],["InvalidAppException","bnetlib\/Exception\/InvalidAppException.html"," < RuntimeException",
                [        ]],["InvalidAppPermissionsException","bnetlib\/Exception\/InvalidAppPermissionsException.html"," < RuntimeException",
                [        ]],["InvalidAppSignatureException","bnetlib\/Exception\/InvalidAppSignatureException.html"," < RuntimeException",
                [        ]],["InvalidArgumentException","bnetlib\/Exception\/InvalidArgumentException.html"," < InvalidArgumentException",
                [        ]],["InvalidAuthHeaderException","bnetlib\/Exception\/InvalidAuthHeaderException.html"," < RuntimeException",
                [        ]],["InvalidServiceNameException","bnetlib\/Exception\/InvalidServiceNameException.html"," < Exception",
                [        ]],["JsonException","bnetlib\/Exception\/JsonException.html"," < RuntimeException",
                [        ]],["LengthException","bnetlib\/Exception\/LengthException.html"," < LengthException",
                [        ]],["LogicException","bnetlib\/Exception\/LogicException.html"," < LogicException",
                [        ]],["PageNotFoundException","bnetlib\/Exception\/PageNotFoundException.html"," < RuntimeException",
                [        ]],["RequestBlockedException","bnetlib\/Exception\/RequestBlockedException.html"," < RuntimeException",
                [        ]],["RequestsThrottledException","bnetlib\/Exception\/RequestsThrottledException.html"," < RuntimeException",
                [        ]],["ResponseExceptionInterface","bnetlib\/Exception\/ResponseExceptionInterface.html","",
                [        ]],["RuntimeException","bnetlib\/Exception\/RuntimeException.html"," < RuntimeException",
                [        ]],["ServerErrorException","bnetlib\/Exception\/ServerErrorException.html"," < RuntimeException",
                [        ]],["ServerUnavailableException","bnetlib\/Exception\/ServerUnavailableException.html"," < RuntimeException",
                [        ]],["ServiceNotCreatedException","bnetlib\/Exception\/ServiceNotCreatedException.html"," < Exception",
                [        ]],["UnexpectedResponseException","bnetlib\/Exception\/UnexpectedResponseException.html"," < RuntimeException",
                [        ]],["UnknownErrorException","bnetlib\/Exception\/UnknownErrorException.html"," < RuntimeException",
                [        ]]        ]],["Locale","bnetlib\/Locale.html","",
                [["Locale","bnetlib\/Locale\/Locale.html","",
                [        ]],["LocaleAwareInterface","bnetlib\/Locale\/LocaleAwareInterface.html","",
                [        ]],["LocaleInterface","bnetlib\/Locale\/LocaleInterface.html","",
                [        ]]        ]],["Resource",,"",
                [["Config","bnetlib\/Resource\/Config.html","",
                [["Diablo","bnetlib\/Resource\/Config\/Diablo.html","",
                [["Career","bnetlib\/Resource\/Config\/Diablo\/Career.html","",
                [        ]],["Hero","bnetlib\/Resource\/Config\/Diablo\/Hero.html","",
                [        ]]        ]],["Wow","bnetlib\/Resource\/Config\/Wow.html","",
                [["Achievement","bnetlib\/Resource\/Config\/Wow\/Achievement.html","",
                [        ]],["ArenaLadder","bnetlib\/Resource\/Config\/Wow\/ArenaLadder.html","",
                [        ]],["ArenaTeam","bnetlib\/Resource\/Config\/Wow\/ArenaTeam.html","",
                [        ]],["Auction","bnetlib\/Resource\/Config\/Wow\/Auction.html","",
                [        ]],["AuctionData","bnetlib\/Resource\/Config\/Wow\/AuctionData.html","",
                [        ]],["Battlegroups","bnetlib\/Resource\/Config\/Wow\/Battlegroups.html","",
                [        ]],["Character","bnetlib\/Resource\/Config\/Wow\/Character.html","",
                [        ]],["CharacterAchievements","bnetlib\/Resource\/Config\/Wow\/CharacterAchievements.html","",
                [        ]],["CharacterClasses","bnetlib\/Resource\/Config\/Wow\/CharacterClasses.html","",
                [        ]],["CharacterRaces","bnetlib\/Resource\/Config\/Wow\/CharacterRaces.html","",
                [        ]],["Guild","bnetlib\/Resource\/Config\/Wow\/Guild.html","",
                [        ]],["GuildAchievements","bnetlib\/Resource\/Config\/Wow\/GuildAchievements.html","",
                [        ]],["GuildPerks","bnetlib\/Resource\/Config\/Wow\/GuildPerks.html","",
                [        ]],["GuildRewards","bnetlib\/Resource\/Config\/Wow\/GuildRewards.html","",
                [        ]],["Item","bnetlib\/Resource\/Config\/Wow\/Item.html","",
                [        ]],["ItemClasses","bnetlib\/Resource\/Config\/Wow\/ItemClasses.html","",
                [        ]],["ItemSet","bnetlib\/Resource\/Config\/Wow\/ItemSet.html","",
                [        ]],["Quest","bnetlib\/Resource\/Config\/Wow\/Quest.html","",
                [        ]],["RatedBattlegroundLadder","bnetlib\/Resource\/Config\/Wow\/RatedBattlegroundLadder.html","",
                [        ]],["Realms","bnetlib\/Resource\/Config\/Wow\/Realms.html","",
                [        ]],["Recipe","bnetlib\/Resource\/Config\/Wow\/Recipe.html","",
                [        ]],["Thumbnail","bnetlib\/Resource\/Config\/Wow\/Thumbnail.html","",
                [        ]]        ]],["ConfigurationInterface","bnetlib\/Resource\/Config\/ConfigurationInterface.html","",
                [        ]]        ]],["Entity","bnetlib\/Resource\/Entity.html","",
                [["Diablo","bnetlib\/Resource\/Entity\/Diablo.html","",
                [["Career","bnetlib\/Resource\/Entity\/Diablo\/Career.html","",
                [["Act","bnetlib\/Resource\/Entity\/Diablo\/Career\/Act.html","",
                [        ]],["Artisan","bnetlib\/Resource\/Entity\/Diablo\/Career\/Artisan.html","",
                [        ]],["Kills","bnetlib\/Resource\/Entity\/Diablo\/Career\/Kills.html","",
                [        ]],["Played","bnetlib\/Resource\/Entity\/Diablo\/Career\/Played.html","",
                [        ]],["Progression","bnetlib\/Resource\/Entity\/Diablo\/Career\/Progression.html","",
                [        ]],["Trade","bnetlib\/Resource\/Entity\/Diablo\/Career\/Trade.html","",
                [        ]]        ]],["Hero","bnetlib\/Resource\/Entity\/Diablo\/Hero.html","",
                [["Attributes","bnetlib\/Resource\/Entity\/Diablo\/Hero\/Attributes.html","",
                [        ]],["Hireling","bnetlib\/Resource\/Entity\/Diablo\/Hero\/Hireling.html","",
                [        ]],["Hirelings","bnetlib\/Resource\/Entity\/Diablo\/Hero\/Hirelings.html","",
                [        ]],["Rune","bnetlib\/Resource\/Entity\/Diablo\/Hero\/Rune.html","",
                [        ]],["Skill","bnetlib\/Resource\/Entity\/Diablo\/Hero\/Skill.html","",
                [        ]],["Skills","bnetlib\/Resource\/Entity\/Diablo\/Hero\/Skills.html","",
                [        ]]        ]],["Career","bnetlib\/Resource\/Entity\/Diablo\/Career.html","",
                [        ]],["Hero","bnetlib\/Resource\/Entity\/Diablo\/Hero.html","",
                [        ]]        ]],["Shared","bnetlib\/Resource\/Entity\/Shared.html","",
                [["Fallback","bnetlib\/Resource\/Entity\/Shared\/Fallback.html"," < ArrayObject",
                [        ]],["File","bnetlib\/Resource\/Entity\/Shared\/File.html","",
                [        ]]        ]],["Wow","bnetlib\/Resource\/Entity\/Wow.html","",
                [["Achievements","bnetlib\/Resource\/Entity\/Wow\/Achievements.html","",
                [["Achievement","bnetlib\/Resource\/Entity\/Wow\/Achievements\/Achievement.html","",
                [        ]],["Achievements","bnetlib\/Resource\/Entity\/Wow\/Achievements\/Achievements.html","",
                [        ]],["Criteria","bnetlib\/Resource\/Entity\/Wow\/Achievements\/Criteria.html","",
                [        ]],["DataAchievement","bnetlib\/Resource\/Entity\/Wow\/Achievements\/DataAchievement.html","",
                [        ]],["DataAchievements","bnetlib\/Resource\/Entity\/Wow\/Achievements\/DataAchievements.html","",
                [        ]]        ]],["Arena","bnetlib\/Resource\/Entity\/Wow\/Arena.html","",
                [["Character","bnetlib\/Resource\/Entity\/Wow\/Arena\/Character.html"," < Character",
                [        ]],["Statistic","bnetlib\/Resource\/Entity\/Wow\/Arena\/Statistic.html","",
                [        ]]        ]],["Auction","bnetlib\/Resource\/Entity\/Wow\/Auction.html","",
                [["Auction","bnetlib\/Resource\/Entity\/Wow\/Auction\/Auction.html","",
                [        ]],["Faction","bnetlib\/Resource\/Entity\/Wow\/Auction\/Faction.html","",
                [        ]]        ]],["Battlegroups","bnetlib\/Resource\/Entity\/Wow\/Battlegroups.html","",
                [["Battlegroup","bnetlib\/Resource\/Entity\/Wow\/Battlegroups\/Battlegroup.html","",
                [        ]]        ]],["Character","bnetlib\/Resource\/Entity\/Wow\/Character.html","",
                [["Appearance","bnetlib\/Resource\/Entity\/Wow\/Character\/Appearance.html","",
                [        ]],["ArenaTeam","bnetlib\/Resource\/Entity\/Wow\/Character\/ArenaTeam.html"," < ArenaTeam",
                [        ]],["ArenaTeams","bnetlib\/Resource\/Entity\/Wow\/Character\/ArenaTeams.html","",
                [        ]],["ClassData","bnetlib\/Resource\/Entity\/Wow\/Character\/ClassData.html","",
                [        ]],["Faction","bnetlib\/Resource\/Entity\/Wow\/Character\/Faction.html","",
                [        ]],["Feed","bnetlib\/Resource\/Entity\/Wow\/Character\/Feed.html","",
                [        ]],["FeedEntry","bnetlib\/Resource\/Entity\/Wow\/Character\/FeedEntry.html","",
                [        ]],["Glyph","bnetlib\/Resource\/Entity\/Wow\/Character\/Glyph.html","",
                [        ]],["Glyphs","bnetlib\/Resource\/Entity\/Wow\/Character\/Glyphs.html","",
                [        ]],["Guild","bnetlib\/Resource\/Entity\/Wow\/Character\/Guild.html"," < GuildEmblem",
                [        ]],["Instance","bnetlib\/Resource\/Entity\/Wow\/Character\/Instance.html","",
                [        ]],["Item","bnetlib\/Resource\/Entity\/Wow\/Character\/Item.html"," < Reward",
                [        ]],["Items","bnetlib\/Resource\/Entity\/Wow\/Character\/Items.html","",
                [        ]],["Pet","bnetlib\/Resource\/Entity\/Wow\/Character\/Pet.html","",
                [        ]],["Pets","bnetlib\/Resource\/Entity\/Wow\/Character\/Pets.html","",
                [        ]],["Profession","bnetlib\/Resource\/Entity\/Wow\/Character\/Profession.html","",
                [        ]],["Professions","bnetlib\/Resource\/Entity\/Wow\/Character\/Professions.html","",
                [        ]],["Progression","bnetlib\/Resource\/Entity\/Wow\/Character\/Progression.html","",
                [        ]],["Pvp","bnetlib\/Resource\/Entity\/Wow\/Character\/Pvp.html","",
                [        ]],["Race","bnetlib\/Resource\/Entity\/Wow\/Character\/Race.html","",
                [        ]],["RatedBattlegrounds","bnetlib\/Resource\/Entity\/Wow\/Character\/RatedBattlegrounds.html","",
                [        ]],["Record","bnetlib\/Resource\/Entity\/Wow\/Character\/Record.html","",
                [        ]],["Reputation","bnetlib\/Resource\/Entity\/Wow\/Character\/Reputation.html","",
                [        ]],["Stats","bnetlib\/Resource\/Entity\/Wow\/Character\/Stats.html","",
                [        ]],["TalentSpecialization","bnetlib\/Resource\/Entity\/Wow\/Character\/TalentSpecialization.html","",
                [        ]],["Talents","bnetlib\/Resource\/Entity\/Wow\/Character\/Talents.html","",
                [        ]],["Title","bnetlib\/Resource\/Entity\/Wow\/Character\/Title.html","",
                [        ]],["Titles","bnetlib\/Resource\/Entity\/Wow\/Character\/Titles.html","",
                [        ]]        ]],["Guild","bnetlib\/Resource\/Entity\/Wow\/Guild.html","",
                [["Member","bnetlib\/Resource\/Entity\/Wow\/Guild\/Member.html","",
                [        ]],["Members","bnetlib\/Resource\/Entity\/Wow\/Guild\/Members.html","",
                [        ]],["News","bnetlib\/Resource\/Entity\/Wow\/Guild\/News.html","",
                [        ]],["NewsEntry","bnetlib\/Resource\/Entity\/Wow\/Guild\/NewsEntry.html","",
                [        ]],["Perk","bnetlib\/Resource\/Entity\/Wow\/Guild\/Perk.html","",
                [        ]],["Reward","bnetlib\/Resource\/Entity\/Wow\/Guild\/Reward.html","",
                [        ]],["Spell","bnetlib\/Resource\/Entity\/Wow\/Guild\/Spell.html","",
                [        ]]        ]],["Item","bnetlib\/Resource\/Entity\/Wow\/Item.html","",
                [["BonusStats","bnetlib\/Resource\/Entity\/Wow\/Item\/BonusStats.html","",
                [        ]],["ClassData","bnetlib\/Resource\/Entity\/Wow\/Item\/ClassData.html","",
                [        ]],["Reward","bnetlib\/Resource\/Entity\/Wow\/Item\/Reward.html"," < Item",
                [        ]],["SocketInfo","bnetlib\/Resource\/Entity\/Wow\/Item\/SocketInfo.html","",
                [        ]],["Spell","bnetlib\/Resource\/Entity\/Wow\/Item\/Spell.html","",
                [        ]],["Spells","bnetlib\/Resource\/Entity\/Wow\/Item\/Spells.html","",
                [        ]],["Stat","bnetlib\/Resource\/Entity\/Wow\/Item\/Stat.html","",
                [        ]],["WeaponInfo","bnetlib\/Resource\/Entity\/Wow\/Item\/WeaponInfo.html","",
                [        ]]        ]],["ItemSet","bnetlib\/Resource\/Entity\/Wow\/ItemSet.html","",
                [["Bonus","bnetlib\/Resource\/Entity\/Wow\/ItemSet\/Bonus.html","",
                [        ]]        ]],["Realms","bnetlib\/Resource\/Entity\/Wow\/Realms.html","",
                [["PvpArea","bnetlib\/Resource\/Entity\/Wow\/Realms\/PvpArea.html","",
                [        ]],["Realm","bnetlib\/Resource\/Entity\/Wow\/Realms\/Realm.html","",
                [        ]]        ]],["Shared","bnetlib\/Resource\/Entity\/Wow\/Shared.html","",
                [["ArenaTeam","bnetlib\/Resource\/Entity\/Wow\/Shared\/ArenaTeam.html","",
                [        ]],["Character","bnetlib\/Resource\/Entity\/Wow\/Shared\/Character.html","",
                [        ]],["Data","bnetlib\/Resource\/Entity\/Wow\/Shared\/Data.html","",
                [        ]],["GuildEmblem","bnetlib\/Resource\/Entity\/Wow\/Shared\/GuildEmblem.html","",
                [        ]],["Item","bnetlib\/Resource\/Entity\/Wow\/Shared\/Item.html","",
                [        ]],["ListData","bnetlib\/Resource\/Entity\/Wow\/Shared\/ListData.html"," < Data",
                [        ]]        ]],["Achievement","bnetlib\/Resource\/Entity\/Wow\/Achievement.html"," < DataAchievement",
                [        ]],["Achievements","bnetlib\/Resource\/Entity\/Wow\/Achievements.html","",
                [        ]],["ArenaLadder","bnetlib\/Resource\/Entity\/Wow\/ArenaLadder.html","",
                [        ]],["ArenaTeam","bnetlib\/Resource\/Entity\/Wow\/ArenaTeam.html"," < ArenaTeam",
                [        ]],["Auction","bnetlib\/Resource\/Entity\/Wow\/Auction.html","",
                [        ]],["AuctionData","bnetlib\/Resource\/Entity\/Wow\/AuctionData.html","",
                [        ]],["Battlegroups","bnetlib\/Resource\/Entity\/Wow\/Battlegroups.html","",
                [        ]],["Character","bnetlib\/Resource\/Entity\/Wow\/Character.html"," < Character",
                [        ]],["CharacterClasses","bnetlib\/Resource\/Entity\/Wow\/CharacterClasses.html","",
                [        ]],["CharacterRaces","bnetlib\/Resource\/Entity\/Wow\/CharacterRaces.html","",
                [        ]],["Guild","bnetlib\/Resource\/Entity\/Wow\/Guild.html"," < GuildEmblem",
                [        ]],["GuildPerks","bnetlib\/Resource\/Entity\/Wow\/GuildPerks.html","",
                [        ]],["GuildRewards","bnetlib\/Resource\/Entity\/Wow\/GuildRewards.html","",
                [        ]],["Item","bnetlib\/Resource\/Entity\/Wow\/Item.html"," < Item",
                [        ]],["ItemClasses","bnetlib\/Resource\/Entity\/Wow\/ItemClasses.html","",
                [        ]],["ItemSet","bnetlib\/Resource\/Entity\/Wow\/ItemSet.html","",
                [        ]],["Quest","bnetlib\/Resource\/Entity\/Wow\/Quest.html","",
                [        ]],["RatedBattlegroundLadder","bnetlib\/Resource\/Entity\/Wow\/RatedBattlegroundLadder.html","",
                [        ]],["Realms","bnetlib\/Resource\/Entity\/Wow\/Realms.html","",
                [        ]],["Recipe","bnetlib\/Resource\/Entity\/Wow\/Recipe.html","",
                [        ]]        ]],["ConsumeInterface","bnetlib\/Resource\/Entity\/ConsumeInterface.html","",
                [        ]],["EntityInterface","bnetlib\/Resource\/Entity\/EntityInterface.html","",
                [        ]]        ]]        ]],["ServiceLocator","bnetlib\/ServiceLocator.html","",
                [["ServiceLocator","bnetlib\/ServiceLocator\/ServiceLocator.html","",
                [        ]],["ServiceLocatorAwareInterface","bnetlib\/ServiceLocator\/ServiceLocatorAwareInterface.html","",
                [        ]],["ServiceLocatorInterface","bnetlib\/ServiceLocator\/ServiceLocatorInterface.html","",
                [        ]]        ]],["AbstractGame","bnetlib\/AbstractGame.html","",
                [        ]],["Diablo","bnetlib\/Diablo.html"," < AbstractGame",
                [        ]],["UrlUtils","bnetlib\/UrlUtils.html","",
                [        ]],["WorldOfWarcraft","bnetlib\/WorldOfWarcraft.html"," < AbstractGame",
                [        ]]        ]]        ]

