<?php
/**
 * This file is part of the bnetlib Library.
 * Copyright (c) 2012 Eric Boh <cossish@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code. You can also view the
 * LICENSE file online at https://gitbub.com/coss/bnetlib/LISENCE
 *
 * @copyright  2012 Eric Boh <cossish@gmail.com>
 * @license    http://coss.gitbub.com/bnetlib/license.html    MIT License
 */

return array(
  'bnetlib\\AbstractGame' => __DIR__ . DIRECTORY_SEPARATOR . 'AbstractGame.php',
  'bnetlib\\Connection' => __DIR__ . DIRECTORY_SEPARATOR . 'Connection.php',
  'bnetlib\\ConnectionInterface' => __DIR__ . DIRECTORY_SEPARATOR . 'ConnectionInterface.php',
  'bnetlib\\Exception\\BadMethodCallException' => __DIR__ . DIRECTORY_SEPARATOR . 'Exception' . DIRECTORY_SEPARATOR . 'BadMethodCallException.php',
  'bnetlib\\Exception\\CacheException' => __DIR__ . DIRECTORY_SEPARATOR . 'Exception' . DIRECTORY_SEPARATOR . 'CacheException.php',
  'bnetlib\\Exception\\DomainException' => __DIR__ . DIRECTORY_SEPARATOR . 'Exception' . DIRECTORY_SEPARATOR . 'DomainException.php',
  'bnetlib\\Exception\\InvalidAppException' => __DIR__ . DIRECTORY_SEPARATOR . 'Exception' . DIRECTORY_SEPARATOR . 'InvalidAppException.php',
  'bnetlib\\Exception\\InvalidAppPermissionsException' => __DIR__ . DIRECTORY_SEPARATOR . 'Exception' . DIRECTORY_SEPARATOR . 'InvalidAppPermissionsException.php',
  'bnetlib\\Exception\\InvalidAppSignatureException' => __DIR__ . DIRECTORY_SEPARATOR . 'Exception' . DIRECTORY_SEPARATOR . 'InvalidAppSignatureException.php',
  'bnetlib\\Exception\\InvalidArgumentException' => __DIR__ . DIRECTORY_SEPARATOR . 'Exception' . DIRECTORY_SEPARATOR . 'InvalidArgumentException.php',
  'bnetlib\\Exception\\InvalidAuthHeaderException' => __DIR__ . DIRECTORY_SEPARATOR . 'Exception' . DIRECTORY_SEPARATOR . 'InvalidAuthHeaderException.php',
  'bnetlib\\Exception\\JsonException' => __DIR__ . DIRECTORY_SEPARATOR . 'Exception' . DIRECTORY_SEPARATOR . 'JsonException.php',
  'bnetlib\\Exception\\LengthException' => __DIR__ . DIRECTORY_SEPARATOR . 'Exception' . DIRECTORY_SEPARATOR . 'LengthException.php',
  'bnetlib\\Exception\\LogicException' => __DIR__ . DIRECTORY_SEPARATOR . 'Exception' . DIRECTORY_SEPARATOR . 'LogicException.php',
  'bnetlib\\Exception\\PageNotFoundException' => __DIR__ . DIRECTORY_SEPARATOR . 'Exception' . DIRECTORY_SEPARATOR . 'PageNotFoundException.php',
  'bnetlib\\Exception\\RequestBlockedException' => __DIR__ . DIRECTORY_SEPARATOR . 'Exception' . DIRECTORY_SEPARATOR . 'RequestBlockedException.php',
  'bnetlib\\Exception\\RequestsThrottledException' => __DIR__ . DIRECTORY_SEPARATOR . 'Exception' . DIRECTORY_SEPARATOR . 'RequestsThrottledException.php',
  'bnetlib\\Exception\\ResponseException' => __DIR__ . DIRECTORY_SEPARATOR . 'Exception' . DIRECTORY_SEPARATOR . 'ResponseException.php',
  'bnetlib\\Exception\\RuntimeException' => __DIR__ . DIRECTORY_SEPARATOR . 'Exception' . DIRECTORY_SEPARATOR . 'RuntimeException.php',
  'bnetlib\\Exception\\ServerErrorException' => __DIR__ . DIRECTORY_SEPARATOR . 'Exception' . DIRECTORY_SEPARATOR . 'ServerErrorException.php',
  'bnetlib\\Exception\\UnexpectedResponseException' => __DIR__ . DIRECTORY_SEPARATOR . 'Exception' . DIRECTORY_SEPARATOR . 'UnexpectedResponseException.php',
  'bnetlib\\Exception' => __DIR__ . DIRECTORY_SEPARATOR . 'Exception.php',
  'bnetlib\\Locale\\Locale' => __DIR__ . DIRECTORY_SEPARATOR . 'Locale' . DIRECTORY_SEPARATOR . 'Locale.php',
  'bnetlib\\Locale\\LocaleAwareInterface' => __DIR__ . DIRECTORY_SEPARATOR . 'Locale' . DIRECTORY_SEPARATOR . 'LocaleAwareInterface.php',
  'bnetlib\\Locale\\LocaleInterface' => __DIR__ . DIRECTORY_SEPARATOR . 'Locale' . DIRECTORY_SEPARATOR . 'LocaleInterface.php',
  'bnetlib\\Resource\\ConfigurationInterface' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'ConfigurationInterface.php',
  'bnetlib\\Resource\\ConsumeInterface' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'ConsumeInterface.php',
  'bnetlib\\Resource\\ResourceInterface' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'ResourceInterface.php',
  'bnetlib\\Resource\\Shared\\File' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Shared' . DIRECTORY_SEPARATOR . 'File.php',
  'bnetlib\\Resource\\Wow\\Achievements\\Achievement' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Achievements' . DIRECTORY_SEPARATOR . 'Achievement.php',
  'bnetlib\\Resource\\Wow\\Achievements\\Achievements' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Achievements' . DIRECTORY_SEPARATOR . 'Achievements.php',
  'bnetlib\\Resource\\Wow\\Achievements\\DataAchievement' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Achievements' . DIRECTORY_SEPARATOR . 'DataAchievement.php',
  'bnetlib\\Resource\\Wow\\Achievements\\DataAchievements' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Achievements' . DIRECTORY_SEPARATOR . 'DataAchievements.php',
  'bnetlib\\Resource\\Wow\\Achievements' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Achievements.php',
  'bnetlib\\Resource\\Wow\\Arena\\Character' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Arena' . DIRECTORY_SEPARATOR . 'Character.php',
  'bnetlib\\Resource\\Wow\\Arena\\Statistic' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Arena' . DIRECTORY_SEPARATOR . 'Statistic.php',
  'bnetlib\\Resource\\Wow\\ArenaLadder' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'ArenaLadder.php',
  'bnetlib\\Resource\\Wow\\ArenaTeam' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'ArenaTeam.php',
  'bnetlib\\Resource\\Wow\\Auction\\Auction' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Auction' . DIRECTORY_SEPARATOR . 'Auction.php',
  'bnetlib\\Resource\\Wow\\Auction\\Faction' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Auction' . DIRECTORY_SEPARATOR . 'Faction.php',
  'bnetlib\\Resource\\Wow\\Auction' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Auction.php',
  'bnetlib\\Resource\\Wow\\AuctionData' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'AuctionData.php',
  'bnetlib\\Resource\\Wow\\Battlegroups\\Battlegroup' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Battlegroups' . DIRECTORY_SEPARATOR . 'Battlegroup.php',
  'bnetlib\\Resource\\Wow\\Battlegroups' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Battlegroups.php',
  'bnetlib\\Resource\\Wow\\Character\\Appearance' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Character' . DIRECTORY_SEPARATOR . 'Appearance.php',
  'bnetlib\\Resource\\Wow\\Character\\ArenaTeam' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Character' . DIRECTORY_SEPARATOR . 'ArenaTeam.php',
  'bnetlib\\Resource\\Wow\\Character\\ArenaTeams' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Character' . DIRECTORY_SEPARATOR . 'ArenaTeams.php',
  'bnetlib\\Resource\\Wow\\Character\\ClassData' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Character' . DIRECTORY_SEPARATOR . 'ClassData.php',
  'bnetlib\\Resource\\Wow\\Character\\Faction' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Character' . DIRECTORY_SEPARATOR . 'Faction.php',
  'bnetlib\\Resource\\Wow\\Character\\Glyph' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Character' . DIRECTORY_SEPARATOR . 'Glyph.php',
  'bnetlib\\Resource\\Wow\\Character\\Glyphs' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Character' . DIRECTORY_SEPARATOR . 'Glyphs.php',
  'bnetlib\\Resource\\Wow\\Character\\Guild' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Character' . DIRECTORY_SEPARATOR . 'Guild.php',
  'bnetlib\\Resource\\Wow\\Character\\Instance' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Character' . DIRECTORY_SEPARATOR . 'Instance.php',
  'bnetlib\\Resource\\Wow\\Character\\Item' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Character' . DIRECTORY_SEPARATOR . 'Item.php',
  'bnetlib\\Resource\\Wow\\Character\\Items' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Character' . DIRECTORY_SEPARATOR . 'Items.php',
  'bnetlib\\Resource\\Wow\\Character\\Pet' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Character' . DIRECTORY_SEPARATOR . 'Pet.php',
  'bnetlib\\Resource\\Wow\\Character\\Pets' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Character' . DIRECTORY_SEPARATOR . 'Pets.php',
  'bnetlib\\Resource\\Wow\\Character\\Profession' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Character' . DIRECTORY_SEPARATOR . 'Profession.php',
  'bnetlib\\Resource\\Wow\\Character\\Professions' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Character' . DIRECTORY_SEPARATOR . 'Professions.php',
  'bnetlib\\Resource\\Wow\\Character\\Progression' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Character' . DIRECTORY_SEPARATOR . 'Progression.php',
  'bnetlib\\Resource\\Wow\\Character\\Pvp' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Character' . DIRECTORY_SEPARATOR . 'Pvp.php',
  'bnetlib\\Resource\\Wow\\Character\\Race' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Character' . DIRECTORY_SEPARATOR . 'Race.php',
  'bnetlib\\Resource\\Wow\\Character\\RatedBattlegrounds' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Character' . DIRECTORY_SEPARATOR . 'RatedBattlegrounds.php',
  'bnetlib\\Resource\\Wow\\Character\\Reputation' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Character' . DIRECTORY_SEPARATOR . 'Reputation.php',
  'bnetlib\\Resource\\Wow\\Character\\Stats' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Character' . DIRECTORY_SEPARATOR . 'Stats.php',
  'bnetlib\\Resource\\Wow\\Character\\Talents' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Character' . DIRECTORY_SEPARATOR . 'Talents.php',
  'bnetlib\\Resource\\Wow\\Character\\TalentSpecialization' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Character' . DIRECTORY_SEPARATOR . 'TalentSpecialization.php',
  'bnetlib\\Resource\\Wow\\Character\\Title' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Character' . DIRECTORY_SEPARATOR . 'Title.php',
  'bnetlib\\Resource\\Wow\\Character\\Titles' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Character' . DIRECTORY_SEPARATOR . 'Titles.php',
  'bnetlib\\Resource\\Wow\\Character' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Character.php',
  'bnetlib\\Resource\\Wow\\CharacterClasses' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'CharacterClasses.php',
  'bnetlib\\Resource\\Wow\\CharacterRaces' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'CharacterRaces.php',
  'bnetlib\\Resource\\Wow\\Configuration\\ArenaLadder' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Configuration' . DIRECTORY_SEPARATOR . 'ArenaLadder.php',
  'bnetlib\\Resource\\Wow\\Configuration\\ArenaTeam' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Configuration' . DIRECTORY_SEPARATOR . 'ArenaTeam.php',
  'bnetlib\\Resource\\Wow\\Configuration\\Auction' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Configuration' . DIRECTORY_SEPARATOR . 'Auction.php',
  'bnetlib\\Resource\\Wow\\Configuration\\AuctionData' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Configuration' . DIRECTORY_SEPARATOR . 'AuctionData.php',
  'bnetlib\\Resource\\Wow\\Configuration\\Battlegroups' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Configuration' . DIRECTORY_SEPARATOR . 'Battlegroups.php',
  'bnetlib\\Resource\\Wow\\Configuration\\Character' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Configuration' . DIRECTORY_SEPARATOR . 'Character.php',
  'bnetlib\\Resource\\Wow\\Configuration\\CharacterAchievements' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Configuration' . DIRECTORY_SEPARATOR . 'CharacterAchievements.php',
  'bnetlib\\Resource\\Wow\\Configuration\\CharacterClasses' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Configuration' . DIRECTORY_SEPARATOR . 'CharacterClasses.php',
  'bnetlib\\Resource\\Wow\\Configuration\\CharacterRaces' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Configuration' . DIRECTORY_SEPARATOR . 'CharacterRaces.php',
  'bnetlib\\Resource\\Wow\\Configuration\\Guild' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Configuration' . DIRECTORY_SEPARATOR . 'Guild.php',
  'bnetlib\\Resource\\Wow\\Configuration\\GuildAchievements' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Configuration' . DIRECTORY_SEPARATOR . 'GuildAchievements.php',
  'bnetlib\\Resource\\Wow\\Configuration\\GuildPerks' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Configuration' . DIRECTORY_SEPARATOR . 'GuildPerks.php',
  'bnetlib\\Resource\\Wow\\Configuration\\GuildRewards' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Configuration' . DIRECTORY_SEPARATOR . 'GuildRewards.php',
  'bnetlib\\Resource\\Wow\\Configuration\\Item' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Configuration' . DIRECTORY_SEPARATOR . 'Item.php',
  'bnetlib\\Resource\\Wow\\Configuration\\ItemClasses' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Configuration' . DIRECTORY_SEPARATOR . 'ItemClasses.php',
  'bnetlib\\Resource\\Wow\\Configuration\\Quest' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Configuration' . DIRECTORY_SEPARATOR . 'Quest.php',
  'bnetlib\\Resource\\Wow\\Configuration\\Realm' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Configuration' . DIRECTORY_SEPARATOR . 'Realm.php',
  'bnetlib\\Resource\\Wow\\Configuration\\Recipe' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Configuration' . DIRECTORY_SEPARATOR . 'Recipe.php',
  'bnetlib\\Resource\\Wow\\Configuration\\Thumbnail' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Configuration' . DIRECTORY_SEPARATOR . 'Thumbnail.php',
  'bnetlib\\Resource\\Wow\\Guild\\Member' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Guild' . DIRECTORY_SEPARATOR . 'Member.php',
  'bnetlib\\Resource\\Wow\\Guild\\Members' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Guild' . DIRECTORY_SEPARATOR . 'Members.php',
  'bnetlib\\Resource\\Wow\\Guild\\Perk' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Guild' . DIRECTORY_SEPARATOR . 'Perk.php',
  'bnetlib\\Resource\\Wow\\Guild\\Reward' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Guild' . DIRECTORY_SEPARATOR . 'Reward.php',
  'bnetlib\\Resource\\Wow\\Guild\\Spell' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Guild' . DIRECTORY_SEPARATOR . 'Spell.php',
  'bnetlib\\Resource\\Wow\\Guild' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Guild.php',
  'bnetlib\\Resource\\Wow\\GuildPerk' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'GuildPerks.php',
  'bnetlib\\Resource\\Wow\\GuildRewards' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'GuildRewards.php',
  'bnetlib\\Resource\\Wow\\Item\\BonusStats' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Item' . DIRECTORY_SEPARATOR . 'BonusStats.php',
  'bnetlib\\Resource\\Wow\\Item\\ClassData' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Item' . DIRECTORY_SEPARATOR . 'ClassData.php',
  'bnetlib\\Resource\\Wow\\Item\\Reward' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Item' . DIRECTORY_SEPARATOR . 'Reward.php',
  'bnetlib\\Resource\\Wow\\Item\\SocketInfo' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Item' . DIRECTORY_SEPARATOR . 'SocketInfo.php',
  'bnetlib\\Resource\\Wow\\Item\\Spell' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Item' . DIRECTORY_SEPARATOR . 'Spell.php',
  'bnetlib\\Resource\\Wow\\Item\\Spells' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Item' . DIRECTORY_SEPARATOR . 'Spells.php',
  'bnetlib\\Resource\\Wow\\Item\\Stat' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Item' . DIRECTORY_SEPARATOR . 'Stat.php',
  'bnetlib\\Resource\\Wow\\Item\\WeaponInfo' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Item' . DIRECTORY_SEPARATOR . 'WeaponInfo.php',
  'bnetlib\\Resource\\Wow\\Item' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Item.php',
  'bnetlib\\Resource\\Wow\\ItemClasses' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'ItemClasses.php',
  'bnetlib\\Resource\\Wow\\Quest' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Quest.php',
  'bnetlib\\Resource\\Wow\\Recipe' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Recipe.php',
  'bnetlib\\Resource\\Wow\\Shared\\ArenaTeam' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Shared' . DIRECTORY_SEPARATOR . 'ArenaTeam.php',
  'bnetlib\\Resource\\Wow\\Shared\\Character' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Shared' . DIRECTORY_SEPARATOR . 'Character.php',
  'bnetlib\\Resource\\Wow\\Shared\\Data' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Shared' . DIRECTORY_SEPARATOR . 'Data.php',
  'bnetlib\\Resource\\Wow\\Shared\\GuildEmblem' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Shared' . DIRECTORY_SEPARATOR . 'GuildEmblem.php',
  'bnetlib\\Resource\\Wow\\Shared\\Item' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Shared' . DIRECTORY_SEPARATOR . 'Item.php',
  'bnetlib\\Resource\\Wow\\Shared\\ListData' => __DIR__ . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Wow' . DIRECTORY_SEPARATOR . 'Shared' . DIRECTORY_SEPARATOR . 'ListData.php',
  'bnetlib\\UrlUtils' => __DIR__ . DIRECTORY_SEPARATOR . 'UrlUtils.php',
  'bnetlib\\WorldOfWarcraft' => __DIR__ . DIRECTORY_SEPARATOR . 'WorldOfWarcraft.php',
);